### ISSUE TITLE
django_greater_than() no longer working with Django 1.10

### ISSUE THREAD

**Issue by lutuh** [paulocheque/django-smart-autoregister#1]
Hi,

in Django 1.10 the method `django_greater_than('1.7')` returns `False` because the `DJANGO_VERSION` results to `1.1` due to that slice `[0:3]`.

I'm happy to provide a pull request for this bug. I've already checked the Pull Request tips located here (http://django-smart-autoregister.readthedocs.io/en/latest/about.html#pull-requests-tips), but I'm not sure about the project setup so that the tests will run. Do you install Django in a virtual env and then install django-smart-autoregister as a source package in order to work on it? Thanks for any hint on the dev setup regarding this matter.

Cheers
Lucas

**Comment by paulocheque** [comment]
Thanks for reporting! 

Try this:

Then, for the development:
- make prepare
- make deps
- make test

Before creating the PR:
- make tox (test with all python versions)

**Comment by paulocheque** [comment]
I had the same problem in another lib: https://github.com/paulocheque/django-dynamic-fixture/blob/master/runtests.py

 `if django.VERSION >= (1, 7):` should solve this issue.

**Comment by lutuh** [comment]
I am about to commit my changes. Running `make tox`, I notice that the tests are failing with Django 1.7 and Python 3.5. When I stash my changes and run the tests against commit c88e53f (working directory clean), the tests still fail with Django 1.7:

```
(env) [~/source/django-smart-autoregister]$ pip install Django==1.7.11
[...]
(env) [~/source/django-smart-autoregister]$ make test
Django (1, 7, 11, 'final', 0)
Traceback (most recent call last):
  File "runtests.py", line 21, in <module>
    django.setup()
[...]
  File "/home/abc/source/django-smart-autoregister/env/lib/python3.5/site-packages/django/utils/html_parser.py", line 12, in <module>
    HTMLParseError = _html_parser.HTMLParseError
```

Can you confirm this? I am happy to create the PR if this is a known bug.

**Comment by lutuh** [comment]
Pull Request created: #2
This PR drops support for Django 1.7 due to it being outdated and the failing test against the current master and adds support for Django 1.10.
